version: '3.8'

services:
  web:
    build: .
    command: "npm run start"
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis-stack:6379
    volumes:
      - .:/app/
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis-stack
  redis-stack:
    image: redis/redis-stack-server:6.2.4-v3
    ports:
      - 6379:6379
